/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controlador_NativeWiringPI */

#ifndef _Included_controlador_NativeWiringPI
#define _Included_controlador_NativeWiringPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controlador_NativeWiringPI
 * Method:    createOutput
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_controlador_NativeWiringPI_createOutput
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     controlador_NativeWiringPI
 * Method:    createInput
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_controlador_NativeWiringPI_createInput
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     controlador_NativeWiringPI
 * Method:    digitalWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_controlador_NativeWiringPI_digitalWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     controlador_NativeWiringPI
 * Method:    digitalRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_controlador_NativeWiringPI_digitalRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     controlador_NativeWiringPI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controlador_NativeWiringPI_init
  (JNIEnv *, jobject);

/*
 * Class:     controlador_NativeWiringPI
 * Method:    cleanup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_controlador_NativeWiringPI_cleanup
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
