/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controlador_NativeWringPI */

#ifndef _Included_controlador_NativeWringPI
#define _Included_controlador_NativeWringPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controlador_NativeWringPI
 * Method:    createOutput
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_controlador_NativeWringPI_createOutput
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     controlador_NativeWringPI
 * Method:    createInput
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_controlador_NativeWringPI_createInput
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     controlador_NativeWringPI
 * Method:    digitalWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_controlador_NativeWringPI_digitalWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     controlador_NativeWringPI
 * Method:    digitalRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_controlador_NativeWringPI_digitalRead
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
